/*
 * File: app/view/ui/MainView.js
 *
 * This file was generated by Sencha Designer version 2.0.0.
 * http://www.sencha.com/products/designer/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Designer does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.ui.MainView', {
    extend: 'Ext.tab.Panel',

    config: {
        tabBar: {
            docked: 'bottom'
        },
        items: [
            {
                xtype: 'container',
                title: 'Home',
                iconCls: 'home',
                items: [
                    {
                        xtype: 'panel',
                        id: 'GroupListView',
                        items: [
                            {
                                xtype: 'titlebar',
                                docked: 'top',
                                id: 'TopToolbar',
                                title: 'My Groups'
                            },
                            {
                                xtype: 'list',
                                id: 'MyGroupsList',
                                itemTpl: [
                                    '<div>List Item {string}</div>'
                                ]
                            }
                        ]
                    }
                ]
            },
            {
                xtype: 'container',
                cls: [
                    'search'
                ],
                title: 'Search',
                iconCls: 'search',
                items: [
                    {
                        xtype: 'container',
                        items: [
                            {
                                xtype: 'toolbar',
                                docked: 'top',
                                id: 'SearchToolbar',
                                layout: {
                                    align: 'stretchmax',
                                    type: 'hbox'
                                },
                                items: [
                                    {
                                        xtype: 'searchfield',
                                        docked: 'top',
                                        width: '',
                                        label: '',
                                        placeHolder: ' Search'
                                    }
                                ]
                            },
                            {
                                xtype: 'list',
                                id: 'SearchResultsList',
                                itemTpl: [
                                    '<div>List Item {string}</div>'
                                ]
                            }
                        ]
                    }
                ]
            },
            {
                xtype: 'container',
                title: 'Create',
                iconCls: 'add',
                items: [
                    {
                        xtype: 'formpanel',
                        id: 'CreateGroupView',
                        items: [
                            {
                                xtype: 'titlebar',
                                docked: 'top',
                                title: 'Create Group',
                                items: [
                                    {
                                        xtype: 'spacer'
                                    },
                                    {
                                        xtype: 'button',
                                        docked: 'right',
                                        iconAlign: 'right',
                                        text: 'Save',
                                        align: 'right'
                                    }
                                ]
                            },
                            {
                                xtype: 'textfield',
                                id: 'GroupNameField',
                                label: 'Name',
                                labelAlign: 'top'
                            },
                            {
                                xtype: 'textareafield',
                                id: 'GroupDescField',
                                label: 'Description'
                            }
                        ]
                    }
                ]
            },
            {
                xtype: 'container',
                title: 'Settings',
                iconCls: 'settings'
            }
        ]
    }

});