/*
 * File: app/controller/GroupDetailsController.js
 *
 * This file was generated by Sencha Designer version 2.0.0.
 * http://www.sencha.com/products/designer/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Designer does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * You should implement event handling and custom methods in this
 * class.
 */

Ext.define('fishpickle.controller.GroupDetailsController', {
    extend: 'Ext.app.Controller',

    config: {
        stores: [
            'MyGroupsStore'
        ],
        refs: {
            groupDetailsView: 'groupdetailsview',
            mainAppView: 'mainappview'
        },

        control: {
            "#saveGroupButton": {
                tap: 'onSaveButtonTap'
            },
            "#myGroupsList": {
                disclose: 'onMyGroupsListDisclose'
            },
            "#searchResultsList": {
                disclose: 'onSearchResultsListDisclose'
            },
            "#groupDetailsBackButton": {
                tap: 'onBackButtonTap'
            }
        }
    },

    onSaveButtonTap: function(button, e, options) {
        var group = this.getGroupDetailsView().getRecord();
        group.set(this.getGroupDetailsView().getValues());
        if (group.data.id === null) {
            group.getProxy().setUrl(fishpickle.baseURL + 'rest/user/' + fishpickle.currentUser.data.id + '/groups');
        } else {
            group.getProxy().setUrl(fishpickle.baseURL + 'rest/group/');
        }


        group.save({
            callback: function(records, operation, success) {
                this.getMainAppView().setActiveItem(2);
            }
        },
        this
        );
    },

    onMyGroupsListDisclose: function(list, record, target, index, e, options) {
        this.openGroupDetails(record);

    },

    onSearchResultsListDisclose: function(list, record, target, index, e, options) {
        this.openGroupDetails(record);

    },

    openGroupDetails: function(record) {
        this.getGroupDetailsView().setRecord(record);
        this.getMainAppView().setActiveItem(3);

    },

    onBackButtonTap: function(button, e, options) {
        this.getMainAppView().setActiveItem(2);

    }

});