/*
 * File: app/controller/GroupController.js
 *
 * This file was generated by Sencha Designer version 2.0.0.
 * http://www.sencha.com/products/designer/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Designer does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * You should implement event handling and custom methods in this
 * class.
 */

Ext.define('fishpickle.controller.GroupController', {
    extend: 'Ext.app.Controller',

    config: {
        stores: [
            'MyGroupsStore'
        ],
        refs: {
            createGroupFormPanel: 'createGroupFormPanel',
            primaryView: 'primaryview'
        },

        control: {
            "#createGroupView": {
                activate: 'onFormpanelActivate'
            },
            "#saveGroupButton": {
                tap: 'onButtonTap'
            }
        }
    },

    onButtonTap: function(button, e, options) {

        var group = this.getCreateGroupFormPanel().getRecord();
        group.set(this.getCreateGroupFormPanel().getValues());
        group.getProxy().setUrl(fishpickle.baseURL + 'rest/user/1/groups');

        group.save({
            callback: function(records, operation, success) {
                this.getPrimaryView().setActiveItem(0);
            }
        },
        this
        );
    },

    onFormpanelActivate: function(container, newActiveItem, oldActiveItem, options) {

        if (fishpickle.baseURL) {
            //console.log("in activate create group view");
            var group = Ext.create('fishpickle.model.userGroup', { id: '', name: '', description: '', isPrivate: false });
            this.getCreateGroupFormPanel().setRecord(group);
        }
    }

});