/*
 * File: app/controller/MyGroupsController.js
 *
 * This file was generated by Sencha Designer version 2.0.0.
 * http://www.sencha.com/products/designer/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Designer does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('fishpickle.controller.MyGroupsController', {
    extend: 'Ext.app.Controller',

    config: {
        refs: {
            groupDetailsView: 'groupdetailsview',
            joinGroupButton: '#joinGroupButton',
            alreadyMemberLabel: '#alreadyMemberLabel'
        },

        control: {
            "#MainAppView": {
                activeitemchange: 'onPanelActiveItemChange'
            },
            "#myGroupsContainer": {
                activate: 'onContainerActivate'
            },
            "#createGroup": {
                tap: 'onNewGroupButtonTap'
            }
        }
    },

    onPanelActiveItemChange: function(container, value, oldValue, options) {
        if (fishpickle.baseURL && fishpickle.currentUser) {
            //console.log("Panel Active Item Change " + fishpickle.baseURL);
            Ext.getStore("MyGroupsStore").getProxy().setUrl(fishpickle.baseURL + "rest/user/" + fishpickle.currentUser.data.id + "/groups");
            Ext.getStore("MyGroupsStore").load();  
        }
    },

    onContainerActivate: function(container, newActiveItem, oldActiveItem, options) {
        if (fishpickle.baseURL && fishpickle.currentUser) {
            //console.log("Panel Active Item Change " + fishpickle.baseURL);
            Ext.getStore("MyGroupsStore").getProxy().setUrl(fishpickle.baseURL + "rest/user/" + fishpickle.currentUser.data.id + "/groups");
            Ext.getStore("MyGroupsStore").load();  
        }
    },

    onNewGroupButtonTap: function(button, e, options) {
        if (fishpickle.baseURL) {
            //console.log("in activate create group view");
            var group = Ext.create('fishpickle.model.UserGroup', { id: '', name: '', description: '', isPrivate: true });
            this.getGroupDetailsView().setRecord(group);
            this.getJoinGroupButton().setHidden(true);
            this.getAlreadyMemberLabel().setHidden(true);
            this.getApplication().fireEvent('navigateToGroupDetailsView');
        }
    }

});