/*
 * File: app/controller/NavigationController.js
 *
 * This file was generated by Sencha Designer version 2.0.0.
 * http://www.sencha.com/products/designer/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Designer does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('fishpickle.controller.NavigationController', {
    extend: 'Ext.app.Controller',

    config: {
        refs: {
            mainAppView: {
                selector: 'mainappview',
                xtype: 'mainappview'
            },
            mainView: {
                selector: 'mainview',
                xtype: 'mainview'
            }
        }
    },

    init: function() {
        this.getApplication().on([
            { event: 'navigateToLoginView', fn: this.onNavigateToLoginView, scope: this },
            { event: 'navigateToMyGroupsView', fn: this.onNavigateToMyGroupsView, scope: this },
            { event: 'navigateToRegistrationView', fn: this.onNavigateToRegistrationView, scope: this },
            { event: 'navigateToGroupDetailsView', fn: this.onNavigateToGroupDetailsView, scope: this }
        ]);
    },

    onNavigateToLoginView: function() {
        this.getMainAppView().setActiveItem(1);


    },

    onNavigateToMyGroupsView: function() {
        this.getMainAppView().setActiveItem(2);
        this.getMainView().setActiveItem(0);
    },

    onNavigateToRegistrationView: function() {
        this.getMainAppView().setActiveItem(3);
    },

    onNavigateToGroupDetailsView: function() {
        this.getMainAppView().setActiveItem(4);
    }

});