/*
 * File: app/controller/SearchController.js
 *
 * This file was generated by Sencha Designer version 2.0.0.
 * http://www.sencha.com/products/designer/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Designer does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * You should implement event handling and custom methods in this
 * class.
 */

Ext.define('fishpickle.controller.SearchController', {
    extend: 'Ext.app.Controller',

    config: {
        refs: {
            searchResultsList: '#searchResultsList'
        },

        control: {
            "#searchGroupsContainer": {
                activate: 'onContainerActivate'
            },
            "#groupSearchField": {
                keyup: 'onTextfieldKeyup'
            }
        }
    },

    onContainerActivate: function(container, newActiveItem, oldActiveItem, options) {
        if (fishpickle.baseURL) {
            //console.log("Container Activate " + fishpickle.baseURL);
            Ext.getStore("AllGroupsStore").getProxy().setUrl(fishpickle.baseURL + "rest/search/group");
            Ext.getStore("AllGroupsStore").load();  
        }
    }

});