/*
 * File: app/model/User.js
 *
 * This file was generated by Sencha Designer version 2.0.0.
 * http://www.sencha.com/products/designer/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Designer does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('fishpickle.model.User', {
    extend: 'Ext.data.Model',
    config: {
        idProperty: 'uid',
        fields: [
            {
                name: 'id',
                type: 'int'
            },
            {
                name: 'displayName',
                type: 'string'
            },
            {
                name: 'login',
                type: 'string'
            },
            {
                name: 'password',
                type: 'string'
            },
            {
                name: 'email',
                type: 'string'
            },
            {
                name: 'groupIds'
            }
        ],
        proxy: {
            type: 'rest',
            url: 'http://dynamicurl',
            writer: {
                type: 'json',
                encode: true,
                root: 'user'
            },
            reader: {
                type: 'json',
                rootProperty: 'user'
            }
        },
        validations: [
            {
                type: 'presence',
                field: 'login'
            },
            {
                type: 'presence',
                field: 'password'
            },
            {
                type: 'presence',
                field: 'displayName'
            },
            {
                type: 'email',
                field: 'email'
            }
        ]
    }
});