/*
 * File: app/view/AuthenticationView.js
 *
 * This file was generated by Sencha Designer version 2.0.0.
 * http://www.sencha.com/products/designer/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Designer does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('fishpickle.view.AuthenticationView', {
    extend: 'Ext.form.Panel',
    alias: 'widget.authenticationview',

    config: {
        items: [
            {
                xtype: 'container',
                cls: [
                    'titleContainer'
                ],
                items: [
                    {
                        xtype: 'label',
                        html: '<h2>Welcome to Fishpickle</h2>',
                        id: 'welcomeLabel'
                    }
                ]
            },
            {
                xtype: 'titlebar',
                docked: 'top',
                title: 'fishpickle'
            },
            {
                xtype: 'container',
                ui: '',
                layout: {
                    type: 'vbox'
                },
                items: [
                    {
                        xtype: 'fieldset',
                        baseCls: 'fieldSetHeader',
                        cls: [
                            'formFieldSet'
                        ],
                        title: '',
                        items: [
                            {
                                xtype: 'textfield',
                                inputCls: 'fieldSetField',
                                label: 'LOGIN ID',
                                labelCls: 'fieldSetLabel',
                                name: 'login'
                            },
                            {
                                xtype: 'passwordfield',
                                inputCls: 'fieldSetField',
                                label: 'PASSWORD',
                                labelCls: 'fieldSetLabel',
                                name: 'password'
                            }
                        ]
                    }
                ]
            },
            {
                xtype: 'container',
                cls: [
                    'messageContainer'
                ],
                id: 'loginButtonContainer',
                layout: {
                    type: 'hbox'
                },
                items: [
                    {
                        xtype: 'button',
                        cls: 'basicButton',
                        id: 'LoginButton',
                        itemId: 'LoginButton',
                        width: 100,
                        text: 'Login'
                    },
                    {
                        xtype: 'spacer',
                        height: 50
                    },
                    {
                        xtype: 'button',
                        cls: 'basicSecondaryButton',
                        id: 'RegisterButton',
                        itemId: 'RegisterButton',
                        width: 100,
                        text: 'Register'
                    }
                ]
            }
        ]
    }

});