/*
 * File: app/view/GroupDetailsView.js
 *
 * This file was generated by Sencha Designer version 2.0.0.
 * http://www.sencha.com/products/designer/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Designer does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('fishpickle.view.GroupDetailsView', {
    extend: 'Ext.form.Panel',
    alias: 'widget.groupdetailsview',

    config: {
        itemId: '',
        items: [
            {
                xtype: 'container',
                cls: [
                    'titleContainer'
                ],
                items: [
                    {
                        xtype: 'label',
                        html: '<h2>Group Information</h2>',
                        id: 'groupInformationLabel'
                    }
                ]
            },
            {
                xtype: 'fieldset',
                baseCls: ' fieldSetHeader',
                cls: [
                    'formFieldSet'
                ],
                items: [
                    {
                        xtype: 'textfield',
                        id: 'groupNameField',
                        inputCls: 'fieldSetField',
                        label: 'NAME',
                        labelCls: 'fieldSetLabel',
                        labelWidth: '40%',
                        name: 'name'
                    },
                    {
                        xtype: 'textareafield',
                        id: 'groupDescriptionField',
                        inputCls: 'fieldSetField',
                        label: 'INFO',
                        labelCls: 'fieldSetLabel',
                        labelWidth: '40%',
                        name: 'description'
                    },
                    {
                        xtype: 'togglefield',
                        id: 'isPrivateToggle',
                        inputCls: 'fieldSetField',
                        label: 'PRIVATE',
                        labelCls: 'fieldSetLabel',
                        labelWidth: '40%',
                        name: 'isPrivate',
                        value: 1
                    }
                ]
            },
            {
                xtype: 'titlebar',
                docked: 'top',
                id: 'groupDetails',
                title: 'Group Details',
                items: [
                    {
                        xtype: 'button',
                        id: 'groupDetailsBackButton',
                        ui: 'back',
                        text: 'Back'
                    },
                    {
                        xtype: 'button',
                        id: 'saveGroupButton',
                        itemId: 'saveGroupButton',
                        ui: 'action',
                        text: 'Save',
                        align: 'right'
                    }
                ]
            },
            {
                xtype: 'container',
                cls: [
                    'joinButtonContainer'
                ],
                id: 'joinGroupContainer',
                items: [
                    {
                        xtype: 'button',
                        cls: 'joinButton',
                        id: 'joinGroupButton',
                        text: 'Join Group'
                    }
                ]
            },
            {
                xtype: 'container',
                cls: [
                    'messageContainer'
                ],
                items: [
                    {
                        xtype: 'label',
                        html: '<h2>You are a member of this group.</h2>',
                        id: 'alreadyMemberLabel',
                        style: '{color:green}'
                    }
                ]
            },
            {
                xtype: 'toolbar',
                docked: 'bottom',
                items: [
                    {
                        xtype: 'spacer'
                    }
                ]
            }
        ]
    }

});