/*
 * File: app/view/MapView.js
 *
 * This file was generated by Sencha Designer version 2.0.0.
 * http://www.sencha.com/products/designer/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Designer does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('fishpickle.view.MapView', {
    extend: 'Ext.form.Panel',
    alias: 'widget.mapview',

    config: {
        items: [
            {
                xtype: 'toolbar',
                docked: 'top',
                items: [
                    {
                        xtype: 'button',
                        docked: 'right',
                        id: 'getDirectionsButton',
                        ui: 'action',
                        text: 'Get Directions'
                    },
                    {
                        xtype: 'button',
                        docked: 'right',
                        id: 'removePinButton',
                        ui: 'action',
                        text: 'Clear Map'
                    }
                ]
            },
            {
                xtype: 'fieldset',
                title: 'Location',
                items: [
                    {
                        xtype: 'textfield',
                        id: 'mapOrigin',
                        label: 'Origin',
                        name: 'origin'
                    },
                    {
                        xtype: 'textfield',
                        id: 'mapDestination',
                        label: 'Destination',
                        name: 'destination'
                    },
                    {
                        xtype: 'container',
                        layout: {
                            type: 'vbox'
                        },
                        items: [
                            {
                                xtype: 'radiofield',
                                label: 'Walking',
                                name: 'routeType',
                                value: 'W',
                                checked: true
                            },
                            {
                                xtype: 'radiofield',
                                label: 'Driving',
                                name: 'routeType',
                                value: 'D'
                            },
                            {
                                xtype: 'radiofield',
                                label: 'Bicycling',
                                name: 'routeType',
                                value: 'B'
                            }
                        ]
                    }
                ]
            },
            {
                xtype: 'map',
                height: 300,
                id: 'map',
                itemId: 'map',
                useCurrentLocation: true
            }
        ]
    }

});