/*
 * File: app/view/SearchView.js
 *
 * This file was generated by Sencha Designer version 2.0.0.
 * http://www.sencha.com/products/designer/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Designer does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('fishpickle.view.SearchView', {
    extend: 'Ext.Panel',
    alias: 'widget.searchview',

    config: {
        layout: {
            type: 'fit'
        },
        items: [
            {
                xtype: 'toolbar',
                docked: 'top',
                id: 'searchToolbar',
                layout: {
                    align: 'stretchmax',
                    type: 'hbox'
                },
                items: [
                    {
                        xtype: 'searchfield',
                        docked: 'top',
                        id: 'groupSearchField',
                        width: '',
                        label: '',
                        placeHolder: ' Search'
                    }
                ]
            },
            {
                xtype: 'list',
                id: 'searchResultsList',
                ui: 'round',
                emptyText: 'No groups found.',
                itemTpl: [
                    '<div>{name}</div>'
                ],
                store: 'AllGroupsStore',
                onItemDisclosure: true
            }
        ]
    }

});