/*
 * File: app/view/SettingsView.js
 *
 * This file was generated by Sencha Designer version 2.0.0.
 * http://www.sencha.com/products/designer/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Designer does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('fishpickle.view.SettingsView', {
    extend: 'Ext.form.Panel',
    alias: 'widget.settingsview',

    config: {
        items: [
            {
                xtype: 'titlebar',
                docked: 'top',
                title: 'Settings',
                items: [
                    {
                        xtype: 'button',
                        docked: 'right',
                        id: 'saveSettingsButton',
                        itemId: 'saveSettingsButton',
                        ui: 'action',
                        iconAlign: 'right',
                        text: 'Save',
                        align: 'right'
                    }
                ]
            },
            {
                xtype: 'fieldset',
                title: 'Account Information',
                items: [
                    {
                        xtype: 'textfield',
                        label: 'Login',
                        name: 'login',
                        readOnly: true
                    },
                    {
                        xtype: 'textfield',
                        label: 'Name',
                        name: 'displayName',
                        required: true
                    },
                    {
                        xtype: 'emailfield',
                        label: 'Email',
                        name: 'email',
                        required: true,
                        placeHolder: 'email@example.com'
                    },
                    {
                        xtype: 'passwordfield',
                        label: 'Password',
                        name: 'password',
                        required: true
                    }
                ]
            },
            {
                xtype: 'button',
                cls: 'button1',
                id: 'logoutButton',
                ui: 'action',
                width: 100,
                text: 'Log Out'
            }
        ]
    }

});