/*
 * File: app/view/ui/MainAppView.js
 *
 * This file was generated by Sencha Designer version 2.0.0.
 * http://www.sencha.com/products/designer/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Designer does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('fishpickle.view.ui.MainAppView', {
    extend: 'Ext.Panel',
    requires: [
        'fishpickle.view.LoadingView',
        'fishpickle.view.AuthenticationView',
        'fishpickle.view.MainView'
    ],

    config: {
        id: 'MainAppView',
        layout: {
            type: 'card'
        },
        items: [
            {
                xtype: 'loadingview',
                itemId: 'loadingitem'
            },
            {
                xtype: 'authenticationview',
                id: 'LoginView'
            },
            {
                xtype: 'mainview',
                id: 'mainItem'
            }
        ]
    }

});