/*
 * File: app/view/ui/SettingsView.js
 *
 * This file was generated by Sencha Designer version 2.0.0.
 * http://www.sencha.com/products/designer/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Designer does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('fishpickle.view.ui.SettingsView', {
    extend: 'Ext.form.Panel',

    config: {
        layout: {
            type: 'fit'
        },
        items: [
            {
                xtype: 'titlebar',
                docked: 'top',
                title: 'Settings',
                items: [
                    {
                        xtype: 'button',
                        docked: 'right',
                        id: 'saveSettingsButton',
                        itemId: 'saveSettingsButton',
                        iconAlign: 'right',
                        text: 'Save',
                        align: 'right'
                    }
                ]
            },
            {
                xtype: 'textfield',
                docked: 'top',
                id: 'displayName',
                label: 'Display Name',
                labelAlign: 'top'
            },
            {
                xtype: 'emailfield',
                docked: 'top',
                label: 'Email',
                labelAlign: 'top',
                placeHolder: 'email@example.com'
            },
            {
                xtype: 'passwordfield',
                docked: 'top',
                label: 'New Password',
                labelAlign: 'top'
            },
            {
                xtype: 'passwordfield',
                docked: 'top',
                label: 'Confirm Password',
                labelAlign: 'top'
            }
        ]
    }

});